version: '3.8'
services:
 web:
    build: .
    ports:
    - "8080:80"
    container_name: servidor-web-compose
    volumes:
    # Volumen en modo solo lectura (ro)
    - ./index.html:/usr/share/nginx/html/index.html:ro
    # Volumen en modo solo lectura (ro)
    - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    # Reinicia autom√°ticamente si falla el contenedor
    restart: always

